# Generated by Django 5.2.17 on 2026-09-21 16:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability')], max_length=12)),
                ('category', models.CharField(choices=[('cash', 'Cash / bank balance'), ('investment', 'Investment'), ('property', 'Property'), ('retirement', 'Retirement savings'), ('loan', 'Loan'), ('mortgage', 'Home loan'), ('credit', 'Credit card balance'), ('other', 'Other')], max_length=16)),
                ('value_paise', models.PositiveBigIntegerField()),
                ('valued_on', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.family')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value_paise__gte', 0), ('value_paise__lte', 999999999999999)), name='valid_finance_value'), models.CheckConstraint(condition=models.Q(models.Q(('category__in', ['cash', 'investment', 'property', 'retirement', 'other']), ('kind', 'asset')), models.Q(('category__in', ['loan', 'mortgage', 'credit', 'other']), ('kind', 'liability')), _connector='OR'), name='finance_category_matches_kind')],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('area', models.CharField(choices=[('finance', 'Finance'), ('education', 'Education'), ('health', 'Health'), ('lifestyle', 'Lifestyle'), ('other', 'Other')], max_length=16)),
                ('target_date', models.DateField()),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.family')),
            ],
            options={
                'ordering': ['target_date', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='valid_goal_progress'), models.CheckConstraint(condition=models.Q(('area__in', ['finance', 'education', 'health', 'lifestyle', 'other'])), name='valid_goal_area'), models.CheckConstraint(condition=models.Q(models.Q(('progress', 100), ('status', 'completed')), models.Q(('progress__lt', 100), ('status__in', ['active', 'paused'])), _connector='OR'), name='goal_status_matches_progress')],
            },
        ),
    ]
