# Generated by Django 5.2.17 on 2026-09-27 05:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_financialrecord_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailConnection',
            fields=[
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.family')),
                ('credentials', models.TextField(blank=True)),
                ('connected', models.BooleanField(default=False)),
                ('generation', models.UUIDField(default=uuid.uuid4)),
                ('history_id', models.CharField(blank=True, max_length=40)),
                ('full_sync', models.BooleanField(default=True)),
                ('page_token', models.TextField(blank=True)),
                ('baseline_history', models.CharField(blank=True, max_length=40)),
                ('requested', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(null=True)),
                ('last_attempt', models.DateTimeField(null=True)),
                ('last_success', models.DateTimeField(null=True)),
                ('status', models.CharField(default='disconnected', max_length=24)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('lease', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.family')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField()),
                ('category', models.CharField(choices=[('insurance', 'Insurance'), ('tax', 'Tax'), ('property', 'Property'), ('banking', 'Banking / Investment'), ('education', 'Education'), ('identity', 'Identity'), ('medical', 'Medical'), ('travel', 'Travel'), ('other', 'Other')], max_length=16)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('renew_on', models.DateField(blank=True, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checksum', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=32)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('gmail', 'Gmail')], max_length=8)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.family')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vault.familyperson')),
            ],
            options={
                'ordering': ['-starred', '-created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('family', 'checksum'), name='vault_unique_content'), models.CheckConstraint(condition=models.Q(('category__in', ['insurance', 'tax', 'property', 'banking', 'education', 'identity', 'medical', 'travel', 'other'])), name='vault_valid_category'), models.CheckConstraint(condition=models.Q(('source__in', ['manual', 'gmail'])), name='vault_valid_source')],
            },
        ),
    ]
