# Generated by Django 5.2.17 on 2026-09-27 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAttempt',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('session_digest', models.CharField(max_length=64)),
                ('pending', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
